// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//                 <Navbar />
//         <main>{children}</main>
//         <footer className="py-10 text-center border-t border-gray-200 dark:border-white/10 mt-20">
//           <p className="text-gray-500">© 2024 Digital Astra Labs. India & Globally.</p>
//         </footer>
//       </body>
//     </html>
//   );
// }

"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { useState, useEffect } from "react";

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState("dark");

  useEffect(() => {
    const savedTheme = localStorage.getItem("theme") || "dark";
    setTheme(savedTheme);
    document.documentElement.classList.toggle("dark", savedTheme === "dark");
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === "dark" ? "light" : "dark";
    setTheme(newTheme);
    localStorage.setItem("theme", newTheme);
    document.documentElement.classList.toggle("dark", newTheme === "dark");
  };

  return (
    <html lang="en" className="dark">
      <head>
        <title>Digital Astra Labs | Mobile & Web App Development</title>
      </head>
      <body className="antialiased overflow-x-hidden">
        <Navbar toggleTheme={toggleTheme} theme={theme} />
        {children}
      </body>
    </html>
  );
}